# Generated by Django 5.0.6 on 2024-06-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("article_id", models.AutoField(primary_key=True, serialize=False)),
                ("article_heading", models.CharField(max_length=250)),
                ("article_body", models.TextField()),
            ],
        ),
    ]
